### ISSUE TITLE
Tidbit: Migrating Dropbox->Filen via Kubernetes

### ISSUE THREAD

**Issue by adamcharnock** [FilenCloudDienste/filen-desktop#168]
In case it helps anyone, I'm running 200GB migration of Dropbox -> Filen using the following:

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: dropbox-migration
  labels:
    name: dropbox-migration
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dropbox-client
  namespace: dropbox-migration
spec:
  serviceName: "dropbox-client"
  replicas: 1
  selector:
    matchLabels:
      app: dropbox-client
  template:
    metadata:
      labels:
        app: dropbox-client
    spec:
      initContainers:
      - name: setup
        image: busybox
        command: ["/bin/sh", "-c"]
        args:
        - |
          chown -R root:root /home-tmp
        volumeMounts:
        - name: home
          mountPath: /home-tmp
      containers:
      - name: dropbox
        image: acaranta/docker-dropbox
        restartPolicy: Always
        volumeMounts:
        - name: home
          mountPath: /root
      - name: filen-sync
        image: filen/cli:latest
        restartPolicy: Always
        args:
          - "sync"
          - "/dropbox-home/Dropbox:localToCloud:/Dropbox"
          - "--continuous"
          - "--verbose"
        volumeMounts:
          - name: home
            mountPath: /dropbox-home
        env:
        - name: FILEN_EMAIL
          valueFrom:
            secretKeyRef:
              name: filen-credentials
              key: email
        - name: FILEN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: filen-credentials
              key: password
  volumeClaimTemplates:
  - metadata:
      name: home
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 300Gi
```

```
kubectl create secret generic filen-credentials \
             --from-literal=email=adam@example.com \
             --from-literal="password=12345abc" -n dropbox-migration
````
